### ISSUE TITLE
feat request: audition sounds

### ISSUE THREAD

**Issue by abulka** [eclewlow/Prophet6SoundLibrarian#5]
At the moment when you send a program from the software to the P6, it overwrites that location on the P6. Fair enough.

It would be nice if you could audition a patch without actually overwriting anything on the Prophet hardware. The P6 supports this "auditioning" ability. E.g. in Javascript it is something like:

```javascript
  get as_message_audition() {
    let result = new Array()
    result.push(SysEx.SYSEX)
    result.push(SysEx.DSI_ID)
    result.push(SysEx.PROPHET_6_ID)
    result.push(SysEx.TYPE_EDIT_BUFFER_DATA)
    result.push(...this.preset_data_packed)
    result.push(SysEx.EOX)
    return result
  }

static get SYSEX() { return 0b11110000 }  // 240
static get DSI_ID() { return 0b00000001 }
static get PROPHET_6_ID() { return 0b00101101 }
static get TYPE_PROGRAM_DATA() { return 0b00000010 }  // aka message_raw
static get TYPE_EDIT_BUFFER_DATA() {  return 0b00000011 }  // aka as_audition
static get EOX() { return 0b11110111 }  // 247
```

**Comment by eclewlow** [comment]
559ccc698138663c69dd75f70aaa93885d341ed6

Added with release
https://github.com/eclewlow/Prophet6SoundLibrarian/releases/tag/v1.1.5
